apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: app
  labels:
    app: fastapi
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
      tier: backend
  template:
    metadata:
      labels:
        app: fastapi
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: fastapi-backend
        image: acraksplatformpocdevhzi2.azurecr.io/fastapi:__SHA__
        ports:
        - containerPort: 80

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3

        env:
        - name: APP_VERSION
          value: "1.0.0"
        - name: GIT_SHA
          value: "__SHA__"
        - name: BUILD_TIME
          value: "__BUILD_TIME__"
          
      nodeSelector:
          workload: apps
