apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: app
  labels:
    app: fastapi
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: fastapi
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
